// <auto-generated />
using EF_RelationShipsDeleting.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EF_RelationShipsDeleting.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260518100458_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EF_RelationShipsDeleting.Entities.Author", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.HasKey("Id");

                    b.ToTable("Author", (string)null);
                });

            modelBuilder.Entity("EF_RelationShipsDeleting.Entities.AuthorV2", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("AuthorName")
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.HasKey("Id");

                    b.ToTable("AuthorV2", (string)null);
                });

            modelBuilder.Entity("EF_RelationShipsDeleting.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("BookName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.Property<decimal>("Price")
                        .HasColumnType("DECIMAL");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Book", (string)null);
                });

            modelBuilder.Entity("EF_RelationShipsDeleting.Entities.BookV2", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int?>("AuthorV2Id")
                        .HasColumnType("int");

                    b.Property<string>("BookName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.HasKey("Id");

                    b.HasIndex("AuthorV2Id");

                    b.ToTable("BookV2", (string)null);
                });

            modelBuilder.Entity("EF_RelationShipsDeleting.Entities.Book", b =>
                {
                    b.HasOne("EF_RelationShipsDeleting.Entities.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("EF_RelationShipsDeleting.Entities.BookV2", b =>
                {
                    b.HasOne("EF_RelationShipsDeleting.Entities.AuthorV2", "AuthorV2")
                        .WithMany("BookV2s")
                        .HasForeignKey("AuthorV2Id");

                    b.Navigation("AuthorV2");
                });

            modelBuilder.Entity("EF_RelationShipsDeleting.Entities.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("EF_RelationShipsDeleting.Entities.AuthorV2", b =>
                {
                    b.Navigation("BookV2s");
                });
#pragma warning restore 612, 618
        }
    }
}
