### Controller API


### Root


### Server Error

GET https://localhost:7070/api/controller/server-error HTTP/1.1


### Bad Request

POST https://localhost:7070/api/controller/bad-request HTTP/1.1


### Not Found

POST https://localhost:7070/api/controller/not-found HTTP/1.1
Content-Type: application/json


### Unauthorized

POST https://localhost:7070/api/controller/unauthorized HTTP/1.1
Content-Type: application/json


### Conflict

POST https://localhost:7070/api/controller/conflict HTTP/1.1
Content-Type: application/json


### Business Rule Error

POST https://localhost:7070/api/controller/business-rule-error HTTP/1.1
Content-Type: application/json
